// Generated by CoffeeScript 1.5.0
(function() {
  var get_notebook_list, refresh_notebook_name, refreshing;

  get_notebook_list = function() {
    $('#nb-select-name-choose').hide();
    $('#nb-select-spin').show();
    $('#nb-select>select').html('');
    $('#nb [name="choose_notebook"]').val('true');
    return $.get('/settings/notebook/list').done(function(data) {
      var nb, _i, _len, _ref;
      _ref = data.notebooks;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        nb = _ref[_i];
        $('#nb-select>select').append("<option value=\"" + nb.guid + "\">" + nb.name + "</option>");
      }
      return $('#nb-select>select').show();
    }).fail(function(data) {
      $('#nb-select-name-choose').show();
      return $('#nb-select-msg').html('- Failed to load notebooks list.').removeClass('hide');
    }).always(function(data) {
      return $('#nb-select-spin').hide();
    });
  };

  refreshing = false;

  refresh_notebook_name = function() {
    if (refreshing) {
      return;
    }
    refreshing = true;
    $('#nb-select-name-refresh>i').addClass('icon-spin');
    $.get('/settings/notebook/name').fail(function(data) {
      if (data.responseText === 'Evernote Authorization Expired') {
        return window.location.reload();
      } else if (data.responseText === 'Notebook Not Found') {
        $('#nb-select-msg').html('We beleive the notebook has been deleted in your Evernote account.<br>Please send a notebook reset request to support.').removeClass('hide');
        $('#nb-select-name-refresh>i').hide();
        return $('#nb-select-name-show>span').hide();
      } else {
        $('#nb-select-name-refresh>i').hide();
        return $('#nb-select-msg').html(' - Failed. Please try again later.').removeClass('hide');
      }
    }).done(function(data) {
      $('#nb-select-name-show>span').html(data.name);
      return $('#nb-select-name-refresh>i').removeClass('icon-spin');
    });
    return refreshing = false;
  };

  $('#menu a').click(function(e) {
    e.preventDefault();
    return $(this).tab('show');
  });

  $('.kl-tooltip').tooltip();

  $('#nb-select-name-list').click(function() {
    get_notebook_list();
    return false;
  });

  $('#nb-select-name-refresh').click(function() {
    refresh_notebook_name();
    return false;
  });

  $('#nb').submit(function() {
    if ($('#nb [name="choose_notebook"]').val() === 'true') {
      $('#nb [name="notebook_name"]').val($("#nb-select>select>[value=\"" + ($('#nb-select>select').val()) + "\"]").html());
      $('#nb [name="notebook_guid"]').val($('#nb-select>select').val());
    }
    $('#nb-spin').fadeIn('fast');
    $('#nb-msg').fadeOut().html('');
    $.ajax({
      type: "PUT",
      url: "/settings/notebook",
      data: $(this).serialize()
    }).done(function() {
      $('#nb-msg').html('Settings Saved!').fadeIn().delay(5000).fadeOut();
      if ($('#nb [name="choose_notebook"]').val() === 'true') {
        $('#nb-select>select').hide();
        $('#nb-select-name-show>span').html($('#nb [name="notebook_name"]').val());
        $('#nb-select-name-show').removeClass('hide');
        return $('#nb-select-name-choose').hide();
      }
    }).fail(function() {
      return $('#nb-msg').html('Failed to save.').fadeIn();
    }).always(function() {
      return $('#nb-spin').fadeOut('fast');
    });
    return false;
  });

  $('#f-acct-bio').change(function() {
    if ($('#f-acct-bio').val().length > 500) {
      $('#f-acct-bio-limit').addClass('red');
      $('#f-acct-bio-limit').removeClass('gray');
      return $('#f-acct-btn').addClass('disabled');
    } else {
      $('#f-acct-bio-limit').addClass('gray');
      $('#f-acct-bio-limit').removeClass('red');
      return $('#f-acct-btn').removeClass('disabled');
    }
  });

  $('#form-account').submit(function() {
    if ($('#f-acct-bio').val().length > 500) {
      $('#f-acct-msg').html('Length of bio exceeds the max limit.').fadeIn().delay(3000).fadeOut();
      return false;
    }
    $('#f-acct-spin').show();
    $('#f-acct-msg').fadeOut().html('');
    $.ajax({
      type: "PUT",
      url: "/settings/account",
      data: $(this).serialize()
    }).done(function() {
      return $('#f-acct-msg').html('Settings Saved!').fadeIn().delay(5000).fadeOut();
    }).fail(function() {
      return $('#f-acct-msg').html('Failed to save.').fadeIn();
    }).always(function() {
      return $('#f-acct-spin').hide();
    });
    return false;
  });

}).call(this);
